sarc:
  mongo:
    connection_string: mongodb://readuser:readpwd@localhost:8123/sarc
    database_name: sarc
  cache: "./sarc-cache"
  loki:
    uri: https://localhost/loki
  tempo:
    uri: https://localhost/tempo
